apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-prom
      protocol: HTTP
    # tls:
    #   mode: SIMPLE
    #   serverCertificate: sds
    #   privateKey: sds
    #   credentialName: telemetry-gw-cert
    hosts:
    - "prometheus.istio.apps.k8s.nestgroup.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system
spec:
  hosts:
  - "prometheus.istio.apps.k8s.nestgroup.net"
  gateways:
  - prometheus-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: prometheus
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: istio-system
spec:
  host: prometheus
  trafficPolicy:
    tls:
      mode: DISABLE
