---
- name: Add Docker repository key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: hkp://ha.pool.sks-keyservers.net
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    mode: 644
    update_cache: yes
    state: present

- name: Install Docker CE
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io



- name: Add users to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

# - name: Copy daemon.json configuration file for docker
#   copy:
#     src: daemon.json
#     dest: /etc/docker/daemon.json
#     owner: root
#     group: root
#     mode: 0644
#   notify:
#     - Reload systemd
#     - Restart docker service
